fix(refreshBIDSDatasetsIndex): handle user with no dataset found
This fixes the following error received for user with no existing dataset during hip web app loading:

```output
[Nest] 3448762  - 03/21/2023, 2:52:55 PM   ERROR [ToolsService] HttpException: parse_exception
        Root causes:
                parse_exception: request body or source parameter is required

/home/stourbie/Softwares/HIP/frontend/gateway/src/tools/tools.service.ts:1352
                        throw new HttpException(e.message, e.status || HttpStatus.BAD_REQUEST)
         ^
HttpException: parse_exception
        Root causes:
                parse_exception: request body or source parameter is required
    at ToolsService.refreshBIDSDatasetsIndex (/home/stourbie/Softwares/HIP/frontend/gateway/src/tools/tools.service.ts:1352:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```